apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: v0wd5mi5u-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/v0wd5mi5u-java-springboot-gitops